export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f5faf8",
        "surface-dim": "#d6dbd9",
        "surface-bright": "#f5faf8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f5f2",
        "surface-container": "#eaefed",
        "surface-container-high": "#e4e9e7",
        "surface-container-highest": "#dee4e1",
        "on-surface": "#171d1c",
        "on-surface-variant": "#3d4947",
        "inverse-surface": "#2c3130",
        "inverse-on-surface": "#edf2f0",
        outline: "#6d7a77",
        "outline-variant": "#bcc9c6",
        "surface-tint": "#006a61",
        primary: "#00685f",
        "on-primary": "#ffffff",
        "primary-container": "#008378",
        "on-primary-container": "#f4fffc",
        "inverse-primary": "#6bd8cb",
        secondary: "#006c49",
        "on-secondary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        tertiary: "#924628",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b05e3d",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        warning: "#935100",
        "on-warning": "#ffffff",
        "warning-container": "#ffdcbd",
        "on-warning-container": "#2f1500",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb59a",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#773215",
        background: "#f5faf8",
        "on-background": "#171d1c",
        "surface-variant": "#dee4e1",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", fontWeight: "600", letterSpacing: "-0.01em" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" },
        ],
      },
      spacing: {
        unit: "8px",
        "container-p-mobile": "16px",
        "container-p-desktop": "32px",
        gutter: "24px",
        "section-gap": "40px",
      },
      borderRadius: {
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        soft: "0px 4px 6px -1px rgba(0, 0, 0, 0.05)",
        elevated: "0px 10px 15px -3px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
